// Generated by clientgen from the byte-verified OpenAPI 3.1 document.
// Do not edit: regenerate (the gate, issue #6, diffs this file in CI).
// Strict types, no coercion: a response is the interface it declares,
// or a ProblemError the caller must handle.

export class ProblemError extends Error { constructor(public problem: Problem) { super(problem.title); } }

export interface NewUser {
  name: string;
  email?: string;
  age?: number;
  role?: string;
  tags?: Array<string>;
}


export interface User {
  id: number;
  name: string;
  email?: string;
  age?: number;
  role?: string;
  tags?: Array<string>;
}


export interface Page {
  total: number;
  items: Array<{ id: number; name: string; email?: string; age?: number; role?: string; tags?: Array<string>;  }>;
}


export interface Problem {
  type: string;
  title: string;
  status: number;
  detail?: string;
  count?: number;
  errors?: Array<{ pointer: string; code: string; detail: string;  }>;
}


export async function health(): Promise<{ ok: boolean;  }> {
  return request("get", `/health`, undefined, undefined);
}

export async function listUsers(options?: { limit?: number, offset?: number }): Promise<Page> {
  return request("get", `/users`, options, undefined);
}

export async function createUser(body: NewUser): Promise<User> {
  return request("post", `/users`, undefined, body);
}

export async function getUser(id: number): Promise<User> {
  return request("get", `/users/${id}`, undefined, undefined);
}

export async function deleteUser(id: number): Promise<void> {
  return request("delete", `/users/${id}`, undefined, undefined);
}

const base = "";

async function request<T>(method: string, path: string, query: Record<string, unknown> | undefined, body: unknown): Promise<T> {
  const url = new URL(base + path, globalThis.location.href);
  if (query) for (const [k, v] of Object.entries(query)) if (v !== undefined) url.searchParams.set(k, String(v));
  const res = await fetch(url, { method, headers: body === undefined ? undefined : { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
  const type = res.headers.get("Content-Type") ?? "";
  if (type.startsWith("application/problem+json")) { throw new ProblemError(await res.json()); }
  if (!res.ok) { throw new ProblemError({ type: "about:blank", title: res.statusText, status: res.status }); }
  if (res.status === 204) { return undefined as T; }
  return await res.json() as T;
}
