# Generated by clientgen from the byte-verified OpenAPI 3.1 document. DO NOT EDIT.
# The gate (issue #6) diffs this file in CI. Strict types, no coercion:
# a response is the dataclass it declares, or a ProblemError.

from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, is_dataclass
from typing import Any, cast

@dataclass(frozen=True)
class ProblemDetail:
    pointer: str
    code: str
    detail: str

class ProblemError(Exception):
    # The typed error the caller must handle: application/problem+json.
    # The problem is on .problem; the 422 errors each have pointer/code/detail.

    def __init__(self, problem: Problem) -> None:
        self.problem = problem
        super().__init__(problem.title)

    def __str__(self) -> str:
        return f'{self.problem.title} ({self.problem.status})'

@dataclass(frozen=True)
class NewUser:
    name: str
    email: str | None = None
    age: int | None = None
    role: str | None = None
    tags: list[str] | None = None

@dataclass(frozen=True)
class User:
    id: int
    name: str
    email: str | None = None
    age: int | None = None
    role: str | None = None
    tags: list[str] | None = None

@dataclass(frozen=True)
class Page:
    total: int
    items: list[dict[str, Any]]

@dataclass(frozen=True)
class Problem:
    type: str
    title: str
    status: int
    detail: str | None = None
    count: int | None = None
    errors: list[dict[str, Any]] | None = None

class Client:
    def __init__(self, base_url: str) -> None:
        self.base_url = base_url

    def health(self) -> dict[str, Any]:
        query: dict[str, Any] = {k: v for k, v in cast('list[tuple[str, Any]]', ()) if v is not None}
        return cast('dict[str, Any]', self.request('GET', f'/health', query, None))

    def listUsers(self, *, limit: int | None = None, offset: int | None = None) -> Page:
        query: dict[str, Any] = {k: v for k, v in cast('list[tuple[str, Any]]', (('limit', limit), ('offset', offset), )) if v is not None}
        return cast('Page', self.request('GET', f'/users', query, None))

    def createUser(self, *, body: NewUser) -> User:
        query: dict[str, Any] = {k: v for k, v in cast('list[tuple[str, Any]]', ()) if v is not None}
        return cast('User', self.request('POST', f'/users', query, body))

    def getUser(self, id: int) -> User:
        query: dict[str, Any] = {k: v for k, v in cast('list[tuple[str, Any]]', ()) if v is not None}
        return cast('User', self.request('GET', f'/users/{id}', query, None))

    def deleteUser(self, id: int) -> None:
        query: dict[str, Any] = {k: v for k, v in cast('list[tuple[str, Any]]', ()) if v is not None}
        return cast('None', self.request('DELETE', f'/users/{id}', query, None))

    def request(self, method: str, path: str, query: dict[str, Any], body: Any) -> Any:
        url = self.base_url + path
        if query:
            url += '?' + urllib.parse.urlencode(query)
        data = None
        headers = {}
        if body is not None:
            data = json.dumps(body, default=_json_default).encode()
            headers['Content-Type'] = 'application/json'
        req = urllib.request.Request(url, data=data, headers=headers, method=method)
        try:
            with urllib.request.urlopen(req) as resp:
                raw = resp.read()
                ctype = resp.headers.get('Content-Type', '')
                if ctype.startswith('application/problem+json'):
                    raise ProblemError(_problem_from(json.loads(raw)))
                if not raw:
                    return None
                return json.loads(raw)
        except urllib.error.HTTPError as err:
            raw = err.read()
            try:
                problem = json.loads(raw)
            except Exception:
                problem = {'type': 'about:blank', 'title': err.reason, 'status': err.code}
            raise ProblemError(_problem_from(problem)) from None


def _json_default(o: Any) -> Any:
    if is_dataclass(o):
        return {f.name: v for f in o.__dataclass_fields__.values() if (v := getattr(o, f.name)) is not None}
    raise TypeError(f'not serializable: {type(o).__name__}')

def _problem_from(raw: dict[str, Any]) -> Problem:
    errors = None
    if 'errors' in raw:
        errors = list(raw['errors'])
    return Problem(
        type=raw.get('type', 'about:blank'),
        title=raw.get('title', ''),
        status=raw.get('status', 0),
        detail=raw.get('detail'),
        count=raw.get('count'),
        errors=errors,
    )
