// Code generated by clientgen from the byte-verified OpenAPI 3.1 document. DO NOT EDIT.
// The gate (issue #6) diffs this file in CI.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

type ProblemError struct{ Problem Problem }

func (e *ProblemError) Error() string { return fmt.Sprintf("%s (%d)", e.Problem.Title, e.Problem.Status) }

type NewUser struct {
	Name string `json:"name"`
	Email string `json:"email,omitempty"`
	Age int `json:"age,omitempty"`
	Role string `json:"role,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

type User struct {
	Id int `json:"id"`
	Name string `json:"name"`
	Email string `json:"email,omitempty"`
	Age int `json:"age,omitempty"`
	Role string `json:"role,omitempty"`
	Tags []string `json:"tags,omitempty"`
}

type Page struct {
	Total int `json:"total"`
	Items []struct { id int; name string; email string; age int; role string; tags []string;  } `json:"items"`
}

type Problem struct {
	Type string `json:"type"`
	Title string `json:"title"`
	Status int `json:"status"`
	Detail string `json:"detail,omitempty"`
	Count int `json:"count,omitempty"`
	Errors []struct { pointer string; code string; detail string;  } `json:"errors,omitempty"`
}

func health(c *Client) (struct { ok bool;  }, error) {
	resp, err := c.do("GET", c.fmtPath(`/health`), nil, nil)
	if err != nil {
		var zero struct { ok bool;  }
		return zero, err
	}
	return decode[struct { ok bool;  }](resp)
}

func listUsers(c *Client, options *listUsersOptions) (Page, error) {
	resp, err := c.do("GET", c.fmtPath(`/users`), options, nil)
	if err != nil {
		var zero Page
		return zero, err
	}
	return decode[Page](resp)
}

type listUsersOptions struct {
	Limit int
	Offset int
}

func (o *listUsersOptions) query() url.Values {
	v := url.Values{}
	if o.Limit != 0 { v.Set("limit", strconv.Itoa(o.Limit)) }
	if o.Offset != 0 { v.Set("offset", strconv.Itoa(o.Offset)) }
	return v
}

func createUser(c *Client, body *NewUser) (User, error) {
	resp, err := c.do("POST", c.fmtPath(`/users`), nil, body)
	if err != nil {
		var zero User
		return zero, err
	}
	return decode[User](resp)
}

func getUser(c *Client, id int) (User, error) {
	resp, err := c.do("GET", c.fmtPath(`/users/%s`, id), nil, nil)
	if err != nil {
		var zero User
		return zero, err
	}
	return decode[User](resp)
}

func deleteUser(c *Client, id int) (struct{}, error) {
	resp, err := c.do("DELETE", c.fmtPath(`/users/%s`, id), nil, nil)
	if err != nil {
		var zero struct{}
		return zero, err
	}
	return decode[struct{}](resp)
}

type Client struct {
	BaseURL string
	HTTP    *http.Client
}

func NewClient(baseURL string) *Client { return &Client{BaseURL: baseURL, HTTP: http.DefaultClient} }

func (c *Client) fmtPath(format string, args ...int) string {
	strs := make([]any, len(args))
	for i, a := range args { strs[i] = strconv.Itoa(a) }
	return fmt.Sprintf(format, strs...)
}

type querier interface{ query() url.Values }

func (c *Client) do(method, path string, options querier, body any) (*http.Response, error) {
	u, err := url.Parse(c.BaseURL + path)
	if err != nil { return nil, err }
	if options != nil { u.RawQuery = options.query().Encode() }
	var rd io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil { return nil, err }
		rd = bytes.NewReader(b)
	}
	req, err := http.NewRequest(method, u.String(), rd)
	if err != nil { return nil, err }
	if body != nil { req.Header.Set("Content-Type", "application/json") }
	return c.HTTP.Do(req)
}

func decode[T any](resp *http.Response) (T, error) {
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil { var zero T; return zero, err }
	if ct := resp.Header.Get("Content-Type"); strings.HasPrefix(ct, "application/problem+json") {
		var p Problem
		if err := json.Unmarshal(body, &p); err != nil { var zero T; return zero, err }
		var zero T
		return zero, &ProblemError{Problem: p}
	}
	if resp.StatusCode >= 400 {
		var zero T
		return zero, &ProblemError{Problem: Problem{Type: "about:blank", Title: http.StatusText(resp.StatusCode), Status: resp.StatusCode}}
	}
	var result T
	if len(body) == 0 { return result, nil }
	if err := json.Unmarshal(body, &result); err != nil { var zero T; return zero, err }
	return result, nil
}
